# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_clone', '0005_auto_20170718_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='picture',
            new_name='photo',
        ),
    ]
