# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_clone', '0008_auto_20170719_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
